###

POST http://localhost:8080/api/token/
#POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "username": "biggie",
  "password": "okioloigi"
}

###

GET http://localhost:8080/api/users/

###

POST http://localhost:8080/api/user/wordlist/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODc5ODM4LCJpYXQiOjE3NDg4NzYyMzgsImp0aSI6IjZlM2I5OTMwMmYxMjQyNjU5NjVhN2ZiMTM3ODI1OGFmIiwidXNlcl9pZCI6Nn0.p3syd6EeC8CSQJmkWE6UkeE09qZA6OFBS0ZJEZ2T7lo

{
  "name": "super duper",
  "words": ["sigma", "sssigma", "boy"]
}

###
GET http://localhost:8080/api/user/wordlist/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTY1MDk3LCJpYXQiOjE3NDg5NjE0OTcsImp0aSI6IjcwYjRiOWUwNGU2NzRkYmRhYjE1NjFjZmJmNDIzNDgxIiwidXNlcl9pZCI6Nn0.ZfPKiEjaPdOZYGX0e3c7IuCLzDsf5KZEumJlY071p10


###
DELETE http://localhost:8080/api/user/wordlist/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NzAxNDE3LCJpYXQiOjE3NDg2OTc4MTcsImp0aSI6ImUwYTU1YTEzMTljNDRjZDI5MzgzZThlMTJmOWU0NzkxIiwidXNlcl9pZCI6Nn0.o9gxTlhNHunFmxPBei3Rhkdy5mrvvLgJD0DI3H2Ki9k

###
OPTIONS http://localhost:8080/api/user/wordlist/33/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTY1MDk3LCJpYXQiOjE3NDg5NjE0OTcsImp0aSI6IjcwYjRiOWUwNGU2NzRkYmRhYjE1NjFjZmJmNDIzNDgxIiwidXNlcl9pZCI6Nn0.ZfPKiEjaPdOZYGX0e3c7IuCLzDsf5KZEumJlY071p10

###
PATCH http://localhost:8080/api/auth/user/6/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MTYzNjEzLCJpYXQiOjE3NDkxNjAwMTMsImp0aSI6IjE3MzdmY2FjMzBhNTQ4NDFiNmE4YzE1MjMwYTVkZmE1IiwidXNlcl9pZCI6Nn0.oJS6HQSYXTyIbsok7OuL-cYF3Fs-xgPYo3zQI7-0k10

{
  "username": "biggie"
}

###
GET http://localhost:8080/api/auth/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MTYzNjEzLCJpYXQiOjE3NDkxNjAwMTMsImp0aSI6IjE3MzdmY2FjMzBhNTQ4NDFiNmE4YzE1MjMwYTVkZmE1IiwidXNlcl9pZCI6Nn0.oJS6HQSYXTyIbsok7OuL-cYF3Fs-xgPYo3zQI7-0k10
